// Copyright 2023 Yusuke Fredrick Tsutsumi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package proto

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/aep-dev/aepc/parser"
	"github.com/jhump/protoreflect/desc/builder"
	"github.com/jhump/protoreflect/desc/protoprint"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/types/descriptorpb"
)

var capitalizer cases.Caser

func init() {
	capitalizer = cases.Title(language.AmericanEnglish)
}

func WriteServiceToProto(ps *parser.ParsedService) ([]byte, error) {
	fb := builder.NewFile("test.proto")
	fb.IsProto3 = true
	fb.SetComments(builder.Comments{
		LeadingComment: "this file is autogenerated by aepc",
	})
	pServiceName := toProtoServiceName(ps.Name)
	serviceNameAsLower := fmt.Sprintf("/%s", strings.ToLower(pServiceName))
	fo := &descriptorpb.FileOptions{
		GoPackage: &serviceNameAsLower,
	}
	fb.SetOptions(fo)
	sb := builder.NewService(pServiceName)
	sb.SetComments(builder.Comments{
		LeadingComment: "A service.",
	})
	for _, r := range getSortedResources(ps.ResourceByType) {
		err := AddResource(r, fb, sb)
		if err != nil {
			return []byte{}, fmt.Errorf("adding resource %v failed: %w", r.Kind, err)
		}
	}
	fb.AddService(sb)
	fd, err := fb.Build()
	if err != nil {
		return []byte{}, fmt.Errorf("unable to build service file %v: %w", fb.GetName(), err)
	}
	printer := protoprint.Printer{}
	var output bytes.Buffer
	err = printer.PrintProtoFile(fd, &output)
	if err != nil {
		return []byte{}, err
	}
	return output.Bytes(), nil
}

func toProtoServiceName(serviceName string) string {
	parts := strings.SplitN(serviceName, ".", 2)
	return capitalizer.String(parts[0])
}

func getSortedResources(prsByString map[string]*parser.ParsedResource) []*parser.ParsedResource {
	keys := []string{}
	for k := range prsByString {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	resources := make([]*parser.ParsedResource, 0, len(keys))
	for _, k := range keys {
		resources = append(resources, prsByString[k])
	}
	return resources
}
