components:
  schemas:
    book:
      properties:
        author:
          items:
            properties:
              firstName:
                type: string
              lastName:
                type: string
            type: object
            x-aep-field-numbers:
              "1": firstName
              "2": lastName
          type: array
        edition:
          format: int32
          type: integer
        isbn:
          items:
            type: string
          type: array
        path:
          readOnly: true
          type: string
        price:
          format: float
          type: number
        published:
          type: boolean
      required:
      - isbn
      - price
      - published
      type: object
      x-aep-field-numbers:
        "0": author
        "1": isbn
        "2": price
        "3": published
        "4": edition
        "10018": path
      x-aep-resource:
        parents:
        - publisher
        patterns:
        - publishers/{publisher}/books/{book}
        plural: books
        singular: book
    book-edition:
      properties:
        displayname:
          type: string
        path:
          readOnly: true
          type: string
      required:
      - displayname
      type: object
      x-aep-field-numbers:
        "1": displayname
        "10018": path
      x-aep-resource:
        parents:
        - book
        patterns:
        - publishers/{publisher}/books/{book}/editions/{book-edition}
        plural: book-editions
        singular: book-edition
    isbn:
      properties:
        path:
          readOnly: true
          type: string
      type: object
      x-aep-field-numbers:
        "10018": path
      x-aep-resource:
        patterns:
        - isbns/{isbn}
        plural: isbns
        singular: isbn
    publisher:
      properties:
        description:
          type: string
        path:
          readOnly: true
          type: string
      type: object
      x-aep-field-numbers:
        "1": description
        "10018": path
      x-aep-resource:
        patterns:
        - publishers/{publisher}
        plural: publishers
        singular: publisher
info:
  description: An API for bookstore.example.com
  title: bookstore.example.com
  version: version not set
openapi: 3.1.0
paths:
  /isbns:
    post:
      description: Create method for isbn
      operationId: isbn.create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/isbn'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/isbn'
          description: Successful response
      summary: ""
  /publishers:
    get:
      description: List method for publisher
      operationId: publisher.list
      parameters:
      - description: ""
        in: query
        name: max_page_size
        required: false
        schema:
          type: integer
      - description: ""
        in: query
        name: page_token
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  results:
                    items:
                      $ref: '#/components/schemas/publisher'
                    type: array
                type: object
          description: Successful response
      summary: ""
    post:
      description: Create method for publisher
      operationId: publisher.create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publisher'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
      summary: ""
  /publishers/{publisher}:
    delete:
      description: Delete method for publisher
      operationId: publisher.delete
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: query
        name: force
        required: false
        schema:
          type: boolean
      responses:
        "204":
          content:
            application/json:
              schema: {}
          description: Successful response
      summary: ""
    get:
      description: Get method for publisher
      operationId: publisher.get
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
      summary: ""
    patch:
      description: Update method for publisher
      operationId: publisher.update
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publisher'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
      summary: ""
    put:
      description: Apply method for publisher
      operationId: publisher.apply
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publisher'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
      summary: ""
  /publishers/{publisher}/books:
    get:
      description: List method for book
      operationId: book.list
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: query
        name: max_page_size
        required: false
        schema:
          type: integer
      - description: ""
        in: query
        name: page_token
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  results:
                    items:
                      $ref: '#/components/schemas/book'
                    type: array
                  unreachable:
                    items:
                      type: string
                    type: array
                type: object
          description: Successful response
      summary: ""
    post:
      description: Create method for book
      operationId: book.create
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
      summary: ""
  /publishers/{publisher}/books/{book}:
    delete:
      description: Delete method for book
      operationId: book.delete
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      - description: ""
        in: query
        name: force
        required: false
        schema:
          type: boolean
      responses:
        "204":
          content:
            application/json:
              schema: {}
          description: Successful response
      summary: ""
    get:
      description: Get method for book
      operationId: book.get
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
      summary: ""
    patch:
      description: Update method for book
      operationId: book.update
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
      summary: ""
    put:
      description: Apply method for book
      operationId: book.apply
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
      summary: ""
  /publishers/{publisher}/books/{book}/editions:
    get:
      description: List method for book-edition
      operationId: book-edition.list
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      - description: ""
        in: query
        name: max_page_size
        required: false
        schema:
          type: integer
      - description: ""
        in: query
        name: page_token
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  results:
                    items:
                      $ref: '#/components/schemas/book-edition'
                    type: array
                type: object
          description: Successful response
      summary: ""
    post:
      description: Create method for book-edition
      operationId: book-edition.create
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book-edition'
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book-edition'
          description: Successful response
      summary: ""
  /publishers/{publisher}/books/{book}/editions/{book-edition}:
    delete:
      description: Delete method for book-edition
      operationId: book-edition.delete
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book-edition
        required: true
        schema:
          type: string
      responses:
        "204":
          content:
            application/json:
              schema: {}
          description: Successful response
      summary: ""
    get:
      description: Get method for book-edition
      operationId: book-edition.get
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book-edition
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book-edition'
          description: Successful response
      summary: ""
  /publishers/{publisher}/books/{book}:archive:
    post:
      description: Custom method archive for book
      operationId: book:archive
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
        description: ""
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
      summary: ""
servers:
- url: http://localhost:8081
