components:
  schemas:
    book:
      properties:
        author:
          items:
            type: object
          type: array
        edition:
          format: int32
          type: integer
        id:
          readOnly: true
          type: string
          x-terraform-id: true
        isbn:
          items:
            type: string
          type: array
        path:
          readOnly: true
          type: string
        price:
          format: float
          type: number
        published:
          type: boolean
      required:
      - isbn
      - price
      - published
      type: object
      x-aep-resource:
        parents:
        - publisher
        patterns:
        - /publishers/{publisher_id}/books/{book_id}
        plural: books
        singular: book
    book-edition:
      properties:
        displayname:
          type: string
        id:
          readOnly: true
          type: string
          x-terraform-id: true
        path:
          readOnly: true
          type: string
      required:
      - displayname
      type: object
      x-aep-resource:
        parents:
        - book
        patterns:
        - /publishers/{publisher_id}/books/{book_id}/editions/{book_edition_id}
        plural: book-editions
        singular: book-edition
    publisher:
      properties:
        description:
          type: string
        id:
          readOnly: true
          type: string
          x-terraform-id: true
        path:
          readOnly: true
          type: string
      type: object
      x-aep-resource:
        patterns:
        - /publishers/{publisher_id}
        plural: publishers
        singular: publisher
info:
  title: bookstore.example.com
  version: version not set
paths:
  /publishers:
    get:
      parameters:
      - in: query
        name: max_page_size
        required: true
        schema: {}
        type: integer
      - in: query
        name: page_token
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            items:
              $ref: '#/components/schemas/publisher'
    post:
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/publisher'
      - in: query
        name: id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/publisher'
  /publishers/{publisher_id}:
    delete:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema: {}
    get:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/publisher'
    patch:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/publisher'
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/publisher'
    put:
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/publisher'
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/publisher'
  /publishers/{publisher_id}/books:
    get:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: query
        name: max_page_size
        required: true
        schema: {}
        type: integer
      - in: query
        name: page_token
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            items:
              $ref: '#/components/schemas/book'
    post:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/book'
      - in: query
        name: id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/book'
  /publishers/{publisher_id}/books/{book_id}:
    delete:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema: {}
    get:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/book'
    patch:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/book'
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/book'
    put:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/book'
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/book'
  /publishers/{publisher_id}/books/{book_id}/editions:
    get:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      - in: query
        name: max_page_size
        required: true
        schema: {}
        type: integer
      - in: query
        name: page_token
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            items:
              $ref: '#/components/schemas/book-edition'
    post:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/components/schemas/book-edition'
      - in: query
        name: id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/book-edition'
  /publishers/{publisher_id}/books/{book_id}/editions/{book_edition_id}:
    delete:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_edition_id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema: {}
    get:
      parameters:
      - in: path
        name: publisher_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_id
        required: true
        schema: {}
        type: string
      - in: path
        name: book_edition_id
        required: true
        schema: {}
        type: string
      responses:
        "200":
          schema:
            $ref: '#/components/schemas/book-edition'
schemes:
- http
servers:
- url: http://localhost:8081
swagger: "2.0"
