name: tests

on:
  push: {}
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3

      - name: Check out code
        uses: actions/checkout@v2

      - name: "test: all tests"
        run: |
          go install github.com/bufbuild/buf/cmd/buf@v1.42.0
          ./scripts/test-all.sh
