name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3

      - name: Check out code
        uses: actions/checkout@v2

      - name: Verify no change to generated files.
        run: |
          ./scripts/verify-goldens.sh

      # - name: Run script
      #   run: |
      #     ./scripts/run-api-linter.sh
