name: tests

on:
  push: {}
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3

      - name: Check out code
        uses: actions/checkout@v2

      - name: "test: no change to generated files."
        run: |
          go install github.com/bufbuild/buf/cmd/buf@v1.42.0
          ./scripts/verify-goldens.sh

      - name: "test: example server function"
        run: |
          ./scripts/test_http_api.sh

      - name: run OAS api-linter
        run: |
          ./scripts/run-oas-linter.sh

      # currently disabled due to api-linter bugs:
      # - https://github.com/aep-dev/api-linter/milestone/1
      # - name: run protobuf api-linter
      #   run: |
      #     ./scripts/run-api-linter.sh
